[build]
  # Directorio donde está el proyecto
  base = "."
  
  # Comando para construir el proyecto
  command = "npm run build"
  
  # Directorio de salida
  publish = "dist"

[build.environment]
  # Versión de Node.js
  NODE_VERSION = "18"

# Redirecciones para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers para archivos estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Formularios (opcional - si usas Netlify Forms)
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Variables de entorno (para Formspree)
[context.production.environment]
  VITE_FORMSPREE_CONTACTO = "https://formspree.io/f/xqaywbjl"
  VITE_FORMSPREE_COMPRA = "https://formspree.io/f/xyznljvn"
  # Agregar variables de Firebase aquí cuando estén listas
  # VITE_FIREBASE_API_KEY = "your_production_api_key"
  # VITE_FIREBASE_AUTH_DOMAIN = "your_project.firebaseapp.com"
  # VITE_FIREBASE_PROJECT_ID = "your_project_id"
  # VITE_FIREBASE_STORAGE_BUCKET = "your_project.appspot.com"
  # VITE_FIREBASE_MESSAGING_SENDER_ID = "your_sender_id"
  # VITE_FIREBASE_APP_ID = "your_app_id"

[context.deploy-preview.environment]
  VITE_FORMSPREE_CONTACTO = "https://formspree.io/f/xqaywbjl"
  VITE_FORMSPREE_COMPRA = "https://formspree.io/f/xyznljvn"
  # Agregar variables de Firebase aquí cuando estén listas
  # VITE_FIREBASE_API_KEY = "your_production_api_key"
  # VITE_FIREBASE_AUTH_DOMAIN = "your_project.firebaseapp.com"
  # VITE_FIREBASE_PROJECT_ID = "your_project_id"
  # VITE_FIREBASE_STORAGE_BUCKET = "your_project.appspot.com"
  # VITE_FIREBASE_MESSAGING_SENDER_ID = "your_sender_id"
  # VITE_FIREBASE_APP_ID = "your_app_id"

