[build]
  # Directorio donde está el proyecto
  base = "."
  
  # Comando para construir el proyecto
  command = "npm run build"
  
  # Directorio de salida
  publish = "dist"

[build.environment]
  # Versión de Node.js
  NODE_VERSION = "18"

# Redirecciones para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers para archivos estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Formularios (opcional - si usas Netlify Forms)
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Variables de entorno (para Formspree)
[context.production.environment]
  VITE_FORMSPREE_CONTACTO = "https://formspree.io/f/YOUR_FORM_ID"
  VITE_FORMSPREE_COMPRA = "https://formspree.io/f/YOUR_FORM_ID_2"

[context.deploy-preview.environment]
  VITE_FORMSPREE_CONTACTO = "https://formspree.io/f/YOUR_FORM_ID"
  VITE_FORMSPREE_COMPRA = "https://formspree.io/f/YOUR_FORM_ID_2"

